### ISSUE TITLE
动态菜单好用吗

### ISSUE THREAD

**Issue by mushroomlb** [tangtanglove/fullstack-frontend#1]
测试了下，菜单无法根据后台传回来的json进行重新刷新，有什么解决方法吗

**Comment by quarkcloudio** [comment]
> 测试了下，菜单无法根据后台传回来的json进行重新刷新，有什么解决方法吗

已经修复，是最新版本ant-design-pro引起的问题

**Comment by mushroomlb** [comment]
赞
