### ISSUE TITLE
几点看法

### ISSUE THREAD

**Issue by mushroomlb** [tangtanglove/fullstack-frontend#4]
详细看了您的代码，感觉会存在几个问题
1 前端代码都集中到几个模板中，不方便做个性化页面
2 所有前端的指令都通过后端传递，增加了网络传输成本，工程大了之后无法适用

我觉得做代码自动生成比单纯的模板要好

**Comment by pangxianfei** [comment]
在linux下开发，无法进行。报库文件大小写不正确。

**Comment by mushroomlb** [comment]
> 在linux下开发，无法进行。报库文件大小写不正确。

windows下不区分大小写，但是在linux中区分，看路由那里大小写是否一致
